### ISSUE TITLE
Wrong date shown when select dates before year 1982 

### ISSUE THREAD

**Issue by anniewey** [davidgovea/react-native-wheel-datepicker#15]
Hi @davidgovea, do you have any idea why the date show will be deducted by 1 day if choose dates on year 1981 and before it? Only happening in `release` build. 

I'm using `DatePicker` with **date** mode

**Comment by davidgovea** [comment]
Thanks for reporting @anniewey! Can you provide a bit more information, or perhaps a screenshot if applicable?

* I'm guessing this affects android only?
* Does the date shown actually change when the <1981 year is selected? Or are you talking about the value provided to the callback?

**Comment by anniewey** [comment]
Sure. I think it's easier to show you in video recording. May find it [here](https://drive.google.com/open?id=1XKDvwHNAeP5bRMfFe6jqZzJERz_R31b2) 
- It affects iOS only
- I think the issue is with the picker where it auto toggled from 23rd to 22nd when selects year 1980

**Comment by anniewey** [comment]
Update: I've managed to solve it using `timeZoneOffsetInMinutes` as suggested in https://github.com/xgfe/react-native-datepicker/issues/95

```
timeZoneOffsetInMinutes={  -1 * new Date(this.props.date).getTimezoneOffset() }
```
